O_TARGET :=	_sub_zlib.o

subdir-y := 

obj-y := adler32.o compress.o crc32.o deflate.o gzclose.o gzlib.o gzread.o minigzip.o\
	gzwrite.o infback.o inffast.o inflate.o inftrees.o trees.o uncompr.o zutil.o example.o

include $(TOPDIR)/Rules.make