O_TARGET := _sub_avllib.o

subdir-y :=

obj-y := avlLib.o strtod.o

extra_include := -I$(DYNLD_TARGET_ROOT) \
				 -I$(DYNLD_TARGET_ROOT)/std \
				 -I$(DYNLD_TARGET_ROOT)/src/core \
				 -I$(DYNLD_TARGET_ROOT)/src/os/unix \



include $(ROOT)/Rules.make

