unexport DYNLD_TARGET_ROOT
unexport DYNLD_TARGET
export DYNLD_TARGET_ROOT := $(shell pwd)
export DYNLD_TARGET := elf

O_TARGET := _sub_elf_example.o

obj-y := elf.o util.o


include $(ROOT)/Rules.make

